config/routes.rb
Rails.application.routes.draw do
  

  resources :comments
  resources :profiles
  resources :posts
  root 'welcome#index'
  resources :users

  resources :sessions

  delete '/logout' => 'sessions#destroy'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
    has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  has_many :comments
  has_one  :profile, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
    # @current_user = 8
  end
  helper_method :current_user

  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
 def create
    @comment = current_user.comments.create whitelisted_params
    redirect_to post_path(@comment.post)
  end

  private

  def whitelisted_params
    params.require(:comment).permit(:comment, :post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
 

  def index
    @posts = Post.all
    
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.create(post_params)
    redirect_to posts_path
  end

  def show
    user = current_user.username
    @post = Post.find params[:id]
  end


    private

# Use strong_parameters for attribute whitelisting
# Be sure to update your create() and update() controller methods.

  def post_params
    params.require(:post).permit(:message, :zip, :user_id)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def index
    @profiles = Profile.all
  end

  def create
   @user_id = current_user.id
   @profile = Profile.new (profile_params)
   @profile.user_id = @user_id
   @profile.save
   redirect_to profile_path(current_user.id)
  end

  def new
    @user = current_user
    @profile = Profile.new
  end

  def show
    @user = User.find(params[:id])
    @profile = Profile.find(@user.id)
  end

  def edit
    @user = User.find(params[:id])
    @profile = Profile.find(params[:id])

  end

  def update
    @user = User.find(params[:id])
    @profile = Profile.find (params[:id])
    @profile.update(profile_params) 
    flash[:alert] = "Updated"
    redirect_to profile_path(current_user.id)
  end

    private

# Use strong_parameters for attribute whitelisting
# Be sure to update your create() and update() controller methods.

  def profile_params
    params.require(:profile).permit(:avatar, :name, :identity, :power, :contact, :user_id)
  end


  

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    username = params[:username]
    password = params[:password]

    @user = User.where(username: username).first
    

    if @user.nil?
      #wrong username case
      flash[:alert] = "Incorrect Credentials"
      redirect_to posts_path
    else #success username case
      if @user.password == password
        session[:user_id] = @user.id
        flash[:alert] = "Welcome Cheese noodle"
        redirect_to posts_path
      else  
        flash[:alert] = "Incorrect Credentials"
        redirect_to posts_path
      end
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:alert] = "Successful Logout"
    redirect_to root_path
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController

   def index
    @users = User.all
  end

  def new
    @user = User.new
    render :layout => false
  end

  def create
    @user = User.create (user_params)
    session[:user_id] = @user.id
    redirect_to new_profile_path
  end
  def show
    @user = User.find params[:id]
    @test = session[:user_id]
  end

  def destroy
    @user =  User.find(params[:id])
    @user.destroy
    flash[:alert] = "Successful Deletion"
    redirect_to users_path
  end
 private

# Use strong_parameters for attribute whitelisting
# Be sure to update your create() and update() controller methods.

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    render :layout => false
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # def current_user
  #   if session[:user_id]
  #     @current_user ||= User.find session[:user_id]
  #   end
  # end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Railsblog</title>
   <link href='http://fonts.googleapis.com/css?family=Orbitron' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<script src="jquery.js"></script>
<script src="typed.js"></script>
<script>
    $(function(){
        $(".element").typed({
            strings: ["WELCOME BACK, AGENT", "Please Log In"],
            typeSpeed: 0
        });
    });
</script>

</head>
<body>

  
  <% if current_user %>
    <div id="header">
      <p class="nav"><%= link_to "| Profile |", profile_path(current_user.id) %></p>
      <p class="nav"><%= link_to "| Edit Profile |", edit_profile_path(current_user.id) %></p>
      <p class="nav"><%= link_to "| All Agents |", users_path %></p>
      <p class="nav"><%= link_to "| All Alerts |", posts_path %></p>
      <p class="nav"><%= link_to "| Send Alert |", new_post_path %></p>
      <p class="nav"><%= link_to "| Log Out |", '/logout', method: :delete %></p>
    </div>
    <%= yield %>
    <% else %>
    <h1 class="formtitle"><span class="element"></span></h1>
    <div class="form">
      <%= form_tag '/sessions' do%>
        <%= text_field_tag :username, nil, placeholder: "CODENAME", class: 'input' %>
        <%= password_field_tag :password, nil, placeholder: "PASSKEY", class: 'input' %>
        <%= submit_tag "ENTER", class: "button" %>
    </div>
      <h3 class='signup'><%= link_to "JOIN THE FIGHT", user_path(:new) %></h3>
      <% end %>
    <% end %>
 

  <% if flash[:alert] %>
    <%= flash[:alert] %>
  <%end%>
 
</body>
</html>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <p><%= link_to User.find(post.user_id).username , post_path(post.id) %> </p>
<% end %>

app/views/posts/new.html.erb
<%= form_for @post do |f| %>
  <%= f.text_area :message, {placeholder: 'Message'} %>
  <%= f.text_field :zip, {placeholder: 'Zip Code'} %>
  <%= f.submit :post %>
<% end %>

app/views/posts/show.html.erb
<p>Message :  <%= @post.message %> </p>
<p>Area :  <%= @post.zip %></p>
<p class="by">Posted by : <%= @post.user.username %></p>
<p class="by">At :  <%= @post.created_at %></p> 

<%= form_for Comment.new do |f| %>
  <%= f.text_area :comment %>
  <%= f.hidden_field :post_id, value: @post.id %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.submit :submit %>
<% end %>

<div>
  <% @post.comments.each do |comment| %>
    <p><%= comment.comment %></p>
    <p class="by">By : <%= User.find(comment.user_id).username  %></p>
  <% end %>
</div>

app/views/profiles/edit.html.erb
<%= form_for @profile do |f| %>
  <%= f.text_field :name, {placeholder: 'super hero name'} %>
  <%= f.text_field :identity, {placeholder: 'real name'} %>
  <%= f.text_field :power, {placeholder: 'what are your superpowers'} %>
  <%= f.text_field :contact, {placeholder: 'how do we contact your'} %>
  <%= f.file_field :avatar %>
  <%= f.submit :edit %>
<% end %>

app/views/profiles/index.html.erb
<% @profiles.each do |profile| %>
<p><%= profile.name %> </p>
<p><%= profile.identity %> </p>
<p><%= profile.power %> </p>
<p><%= profile.contact %> </p>
<p><%= profile.created_at %> </p>
  <%= image_tag profile.avatar.url(:medium) %>
<% end %>

  


  

  

app/views/profiles/new.html.erb
<%= form_for @profile do |f| %>
  <%= f.text_field :name, {placeholder: 'super hero name'} %>
  <%= f.text_field :identity, {placeholder: 'real name'} %>
  <%= f.text_field :power, {placeholder: 'what are your superpowers'} %>
  <%= f.text_field :contact, {placeholder: 'how do we contact your'} %>
  <%= f.file_field :avatar %>
  <%= f.submit :update %>
  <% end %>

app/views/profiles/show.html.erb
<p class="by">Username :  <%= @user.username %> </p>
<p>Hero Name :  <%= @profile.name %></p>
<p>Secret Identity :  <%= @profile.identity %></p>
<p>Powers :  <%= @profile.power %></p>
<p>Contact :  <%= @profile.contact %></p>
<%= image_tag @profile.avatar.url(:medium) %>

app/views/users/index.html.erb
<% @users.each do |user| %>
    <p><%= link_to user.username, profile_path(user.id)%> </p>
<% end %>

app/views/users/new.html.erb
<head>
  <title>JOIN</title>
  <link href='http://fonts.googleapis.com/css?family=Orbitron' rel='stylesheet' type='text/css'>
  <meta charset="utf-8">
  <%= stylesheet_link_tag "users" %>
  <script src="jquery.js"></script>
  <script src="typed.js"></script>
  <script>
    $(function(){
      $(".element").typed({
        strings: ["Do you have what is takes?", "JOIN THE AGENCY"],
        typeSpeed: 0
      });
    });
  </script>
</head>

<% if !current_user %>
<h1 class="formtitle"><span class="element"></span></h1>
<div class="form">
<%= form_for @user do |f| %>
  <%= f.text_field :username, placeholder: 'CODENAME', class: 'input' %>
  <%= f.password_field :password, placeholder: 'PASSKEY', class: 'input' %>

  <%= submit_tag "JOIN", class: 'button' %>
</div>
<% end %>

<% end %>

app/views/users/show.html.erb
<p class="by"><%= link_to @user.username, profile_path(@user.id) %></p>

app/views/welcome/index.html.erb
<!-- <!DOCTYPE HTML> -->
<!-- <html> -->
<body id="welcome">
<head>
  <title>Daily Planet</title>
  <meta charset="utf-8">
  <%= stylesheet_link_tag "welcome" %>

<!-- 
  <body> -->
  <div class="title">
    <div class="glitch" data-text="Daily">Daily</div>
    <a href="/posts" class="logo" title="Secret Entrance"></a>
    <div class="glitch" data-text="Planet">Planet</div>
  </div> 

  <% if flash[:alert] %>
    <%= flash[:alert] %>
  <%end%>

 <!--  </body>

  </html> -->


</body>